<?php
declare(strict_types=1);
namespace TextCraft_Tools_Pro;
defined('ABSPATH') || exit;

class Widget_Currency_Converter extends TextCraft_Tool_Base {
    protected bool $show_preview = false;
    public function get_name(): string { return 'currency_converter'; }
    public function get_title(): string { return 'Currency Converter'; }
    public function get_icon(): string { return 'eicon-currency'; }
    public function get_keywords(): array { return ['currency converter','exchange rate','forex','money converter','currency calculator','exchange rates']; }

    protected function render_tool_content(array $settings): void {
        ?>
        <div class="tc-tool-desc">Convert between 341+ currencies with live exchange rates. Rates are fetched from a free API and cached locally for fast conversions.</div>
        <div class="tc-rsz-options">
            <div class="tc-cc-quick-pairs-section">
                <h4 class="tc-rsz-heading">Quick Pairs</h4>
                <div class="tc-cc-quick-pairs">
                    <button class="tc-btn tc-btn--ghost sel" type="button" data-from="usd" data-to="eur">USD → EUR</button>
                    <button class="tc-btn tc-btn--ghost" type="button" data-from="usd" data-to="gbp">USD → GBP</button>
                    <button class="tc-btn tc-btn--ghost" type="button" data-from="usd" data-to="inr">USD → INR</button>
                    <button class="tc-btn tc-btn--ghost" type="button" data-from="eur" data-to="usd">EUR → USD</button>
                    <button class="tc-btn tc-btn--ghost" type="button" data-from="gbp" data-to="usd">GBP → USD</button>
                    <button class="tc-btn tc-btn--ghost" type="button" data-from="usd" data-to="jpy">USD → JPY</button>
                    <button class="tc-btn tc-btn--ghost" type="button" data-from="usd" data-to="cny">USD → CNY</button>
                    <button class="tc-btn tc-btn--ghost" type="button" data-from="eur" data-to="gbp">EUR → GBP</button>
                </div>
            </div>
            <div class="tc-cc-row">
                <div class="tc-input-group">
                    <label class="tc-label">Amount</label>
                    <input type="number" class="tc-input tc-cc-amount" value="1" min="0" step="any" placeholder="Enter amount">
                </div>
            </div>
            <div class="tc-cc-currency-row">
                <div class="tc-input-group tc-cc-from-group">
                    <label class="tc-label">From</label>
                    <div class="tc-cc-select-wrap">
                        <input type="text" class="tc-input tc-cc-search tc-cc-from-search" placeholder="Search currency..." autocomplete="off">
                        <select class="tc-select tc-cc-from">
                        <option value="1inch">1INCH — 1inch</option>
                        <option value="aave">AAVE — Aave</option>
                        <option value="ada">ADA — Cardano</option>
                        <option value="aed">AED — Emirati Dirham</option>
                        <option value="afn">AFN — Afghan Afghani</option>
                        <option value="agix">AGIX — SingularityNET</option>
                        <option value="akt">AKT — Akash Network</option>
                        <option value="algo">ALGO — Algorand</option>
                        <option value="all">ALL — Albanian Lek</option>
                        <option value="amd">AMD — Armenian Dram</option>
                        <option value="amp">AMP — Amp</option>
                        <option value="ang">ANG — Dutch Guilder</option>
                        <option value="aoa">AOA — Angolan Kwanza</option>
                        <option value="ape">APE — ApeCoin</option>
                        <option value="apt">APT — Aptos</option>
                        <option value="ar">AR — Arweave</option>
                        <option value="arb">ARB — Arbitrum</option>
                        <option value="ars">ARS — Argentine Peso</option>
                        <option value="atom">ATOM — Cosmos</option>
                        <option value="ats">ATS — Austrian Schilling</option>
                        <option value="aud">AUD — Australian Dollar</option>
                        <option value="avax">AVAX — Avalanche</option>
                        <option value="awg">AWG — Aruban or Dutch Guilder</option>
                        <option value="axs">AXS — Axie Infinity</option>
                        <option value="azm">AZM — Azerbaijani Manat</option>
                        <option value="azn">AZN — Azerbaijan Manat</option>
                        <option value="bake">BAKE — BakeryToken</option>
                        <option value="bam">BAM — Bosnian Convertible Mark</option>
                        <option value="bat">BAT — Basic Attention Token</option>
                        <option value="bbd">BBD — Barbadian or Bajan Dollar</option>
                        <option value="bch">BCH — Bitcoin Cash</option>
                        <option value="bdt">BDT — Bangladeshi Taka</option>
                        <option value="bef">BEF — Belgian Franc</option>
                        <option value="bgn">BGN — Bulgarian Lev</option>
                        <option value="bhd">BHD — Bahraini Dinar</option>
                        <option value="bif">BIF — Burundian Franc</option>
                        <option value="bmd">BMD — Bermudian Dollar</option>
                        <option value="bnb">BNB — Binance Coin</option>
                        <option value="bnd">BND — Bruneian Dollar</option>
                        <option value="bob">BOB — Bolivian Bolíviano</option>
                        <option value="brl">BRL — Brazilian Real</option>
                        <option value="bsd">BSD — Bahamian Dollar</option>
                        <option value="bsv">BSV — Bitcoin SV</option>
                        <option value="bsw">BSW — Biswap</option>
                        <option value="btc">BTC — Bitcoin</option>
                        <option value="btcb">BTCB — Bitcoin BEP2</option>
                        <option value="btg">BTG — Bitcoin Gold</option>
                        <option value="btn">BTN — Bhutanese Ngultrum</option>
                        <option value="btt">BTT — BitTorrent</option>
                        <option value="busd">BUSD — Binance USD</option>
                        <option value="bwp">BWP — Botswana Pula</option>
                        <option value="byn">BYN — Belarusian Ruble</option>
                        <option value="byr">BYR — Belarusian Ruble</option>
                        <option value="bzd">BZD — Belizean Dollar</option>
                        <option value="cad">CAD — Canadian Dollar</option>
                        <option value="cake">CAKE — PancakeSwap</option>
                        <option value="cdf">CDF — Congolese Franc</option>
                        <option value="celo">CELO — Celo</option>
                        <option value="cfx">CFX — Conflux</option>
                        <option value="chf">CHF — Swiss Franc</option>
                        <option value="chz">CHZ — Chiliz</option>
                        <option value="clp">CLP — Chilean Peso</option>
                        <option value="cnh">CNH — Chinese Yuan Renminbi Offshore</option>
                        <option value="cny">CNY — Chinese Yuan Renminbi</option>
                        <option value="comp">COMP — Compound</option>
                        <option value="cop">COP — Colombian Peso</option>
                        <option value="crc">CRC — Costa Rican Colon</option>
                        <option value="cro">CRO — Crypto.com Chain</option>
                        <option value="crv">CRV — Curve DAO Token</option>
                        <option value="cspr">CSPR — Casper</option>
                        <option value="cuc">CUC — Cuban Convertible Peso</option>
                        <option value="cup">CUP — Cuban Peso</option>
                        <option value="cve">CVE — Cape Verdean Escudo</option>
                        <option value="cvx">CVX — Convex Finance</option>
                        <option value="cyp">CYP — Cypriot Pound</option>
                        <option value="czk">CZK — Czech Koruna</option>
                        <option value="dai">DAI — DAI</option>
                        <option value="dash">DASH — Digital Cash</option>
                        <option value="dcr">DCR — Decred</option>
                        <option value="dem">DEM — German Deutsche Mark</option>
                        <option value="dfi">DFI — DfiStarter</option>
                        <option value="djf">DJF — Djiboutian Franc</option>
                        <option value="dkk">DKK — Danish Krone</option>
                        <option value="doge">DOGE — Dogecoin</option>
                        <option value="dop">DOP — Dominican Peso</option>
                        <option value="dot">DOT — Polkadot</option>
                        <option value="dydx">DYDX — dYdX</option>
                        <option value="dzd">DZD — Algerian Dinar</option>
                        <option value="eek">EEK — Estonian Kroon</option>
                        <option value="egld">EGLD — Elrond</option>
                        <option value="egp">EGP — Egyptian Pound</option>
                        <option value="enj">ENJ — Enjin Coin</option>
                        <option value="eos">EOS — EOS</option>
                        <option value="ern">ERN — Eritrean Nakfa</option>
                        <option value="esp">ESP — Spanish Peseta</option>
                        <option value="etb">ETB — Ethiopian Birr</option>
                        <option value="etc">ETC — Ethereum Classic</option>
                        <option value="eth">ETH — Ethereum</option>
                        <option value="eur">EUR — Euro</option>
                        <option value="eurc">EURC — </option>
                        <option value="fei">FEI — Fei USD</option>
                        <option value="fil">FIL — Filecoin</option>
                        <option value="fim">FIM — Finnish Markka</option>
                        <option value="fjd">FJD — Fijian Dollar</option>
                        <option value="fkp">FKP — Falkland Island Pound</option>
                        <option value="flow">FLOW — Flow</option>
                        <option value="flr">FLR — FLARE</option>
                        <option value="frax">FRAX — Frax</option>
                        <option value="frf">FRF — French Franc</option>
                        <option value="ftt">FTT — FarmaTrust</option>
                        <option value="gala">GALA — Gala</option>
                        <option value="gbp">GBP — British Pound</option>
                        <option value="gel">GEL — Georgian Lari</option>
                        <option value="ggp">GGP — Guernsey Pound</option>
                        <option value="ghc">GHC — Ghanaian Cedi</option>
                        <option value="ghs">GHS — Ghanaian Cedi</option>
                        <option value="gip">GIP — Gibraltar Pound</option>
                        <option value="gmd">GMD — Gambian Dalasi</option>
                        <option value="gmx">GMX — Goldmaxcoin</option>
                        <option value="gnf">GNF — Guinean Franc</option>
                        <option value="gno">GNO — Gnosis</option>
                        <option value="grd">GRD — Greek Drachma</option>
                        <option value="grt">GRT — The Graph</option>
                        <option value="gt">GT — GateToken</option>
                        <option value="gtq">GTQ — Guatemalan Quetzal</option>
                        <option value="gusd">GUSD — Gemini US Dollar</option>
                        <option value="gyd">GYD — Guyanese Dollar</option>
                        <option value="hbar">HBAR — Hedera</option>
                        <option value="hkd">HKD — Hong Kong Dollar</option>
                        <option value="hnl">HNL — Honduran Lempira</option>
                        <option value="hnt">HNT — Helium</option>
                        <option value="hot">HOT — Hydro Protocol</option>
                        <option value="hrk">HRK — Croatian Kuna</option>
                        <option value="ht">HT — Huobi Token</option>
                        <option value="htg">HTG — Haitian Gourde</option>
                        <option value="huf">HUF — Hungarian Forint</option>
                        <option value="icp">ICP — Internet Computer</option>
                        <option value="idr">IDR — Indonesian Rupiah</option>
                        <option value="iep">IEP — Irish Pound</option>
                        <option value="ils">ILS — Israeli Shekel</option>
                        <option value="imp">IMP — Isle of Man Pound</option>
                        <option value="imx">IMX — Immutable X</option>
                        <option value="inj">INJ — Injective</option>
                        <option value="inr">INR — Indian Rupee</option>
                        <option value="iqd">IQD — Iraqi Dinar</option>
                        <option value="irr">IRR — Iranian Rial</option>
                        <option value="isk">ISK — Icelandic Krona</option>
                        <option value="itl">ITL — Italian Lira</option>
                        <option value="jep">JEP — Jersey Pound</option>
                        <option value="jmd">JMD — Jamaican Dollar</option>
                        <option value="jod">JOD — Jordanian Dinar</option>
                        <option value="jpy">JPY — Japanese Yen</option>
                        <option value="kas">KAS — </option>
                        <option value="kava">KAVA — Kava</option>
                        <option value="kcs">KCS — Kucoin</option>
                        <option value="kda">KDA — Kadena</option>
                        <option value="kes">KES — Kenyan Shilling</option>
                        <option value="kgs">KGS — Kyrgyzstani Som</option>
                        <option value="khr">KHR — Cambodian Riel</option>
                        <option value="klay">KLAY — Klaytn</option>
                        <option value="kmf">KMF — Comorian Franc</option>
                        <option value="knc">KNC — Kyber Network Crystals</option>
                        <option value="kpw">KPW — North Korean Won</option>
                        <option value="krw">KRW — South Korean Won</option>
                        <option value="ksm">KSM — Kusama</option>
                        <option value="kwd">KWD — Kuwaiti Dinar</option>
                        <option value="kyd">KYD — Caymanian Dollar</option>
                        <option value="kzt">KZT — Kazakhstani Tenge</option>
                        <option value="lak">LAK — Lao Kip</option>
                        <option value="lbp">LBP — Lebanese Pound</option>
                        <option value="ldo">LDO — Lido DAO Token</option>
                        <option value="leo">LEO — LEOcoin</option>
                        <option value="link">LINK — Chainlink</option>
                        <option value="lkr">LKR — Sri Lankan Rupee</option>
                        <option value="lrc">LRC — Loopring</option>
                        <option value="lrd">LRD — Liberian Dollar</option>
                        <option value="lsl">LSL — Basotho Loti</option>
                        <option value="ltc">LTC — Litecoin</option>
                        <option value="ltl">LTL — Lithuanian Litas</option>
                        <option value="luf">LUF — Luxembourg Franc</option>
                        <option value="luna">LUNA — Terra</option>
                        <option value="lunc">LUNC — </option>
                        <option value="lvl">LVL — Latvian Lat</option>
                        <option value="lyd">LYD — Libyan Dinar</option>
                        <option value="mad">MAD — Moroccan Dirham</option>
                        <option value="mana">MANA — Mana Coin Decentraland</option>
                        <option value="mbx">MBX — MobieCoin</option>
                        <option value="mdl">MDL — Moldovan Leu</option>
                        <option value="mga">MGA — Malagasy Ariary</option>
                        <option value="mgf">MGF — Malagasy Franc</option>
                        <option value="mina">MINA — Mina</option>
                        <option value="mkd">MKD — Macedonian Denar</option>
                        <option value="mkr">MKR — Maker</option>
                        <option value="mmk">MMK — Burmese Kyat</option>
                        <option value="mnt">MNT — Mongolian Tughrik</option>
                        <option value="mop">MOP — Macau Pataca</option>
                        <option value="mro">MRO — Mauritanian Ouguiya</option>
                        <option value="mru">MRU — Mauritanian Ouguiya</option>
                        <option value="mtl">MTL — Maltese Lira</option>
                        <option value="mur">MUR — Mauritian Rupee</option>
                        <option value="mvr">MVR — Maldivian Rufiyaa</option>
                        <option value="mwk">MWK — Malawian Kwacha</option>
                        <option value="mxn">MXN — Mexican Peso</option>
                        <option value="mxv">MXV — </option>
                        <option value="myr">MYR — Malaysian Ringgit</option>
                        <option value="mzm">MZM — Mozambican Metical</option>
                        <option value="mzn">MZN — Mozambican Metical</option>
                        <option value="nad">NAD — Namibian Dollar</option>
                        <option value="near">NEAR — NEAR Protocol</option>
                        <option value="neo">NEO — NEO</option>
                        <option value="nexo">NEXO — NEXO</option>
                        <option value="nft">NFT — NFT</option>
                        <option value="ngn">NGN — Nigerian Naira</option>
                        <option value="nio">NIO — Nicaraguan Cordoba</option>
                        <option value="nlg">NLG — Dutch Guilder</option>
                        <option value="nok">NOK — Norwegian Krone</option>
                        <option value="npr">NPR — Nepalese Rupee</option>
                        <option value="nzd">NZD — New Zealand Dollar</option>
                        <option value="okb">OKB — Okex</option>
                        <option value="omr">OMR — Omani Rial</option>
                        <option value="one">ONE — Menlo One</option>
                        <option value="op">OP — Optimism</option>
                        <option value="ordi">ORDI — </option>
                        <option value="pab">PAB — Panamanian Balboa</option>
                        <option value="paxg">PAXG — PAX Gold</option>
                        <option value="pen">PEN — Peruvian Sol</option>
                        <option value="pepe">PEPE — </option>
                        <option value="pgk">PGK — Papua New Guinean Kina</option>
                        <option value="php">PHP — Philippine Peso</option>
                        <option value="pi">PI — Plian</option>
                        <option value="pkr">PKR — Pakistani Rupee</option>
                        <option value="pln">PLN — Polish Zloty</option>
                        <option value="pol">POL — Proof Of Liquidity</option>
                        <option value="pte">PTE — Portuguese Escudo</option>
                        <option value="pyg">PYG — Paraguayan Guarani</option>
                        <option value="qar">QAR — Qatari Riyal</option>
                        <option value="qnt">QNT — Quant</option>
                        <option value="qtum">QTUM — QTUM</option>
                        <option value="rol">ROL — Romanian Leu</option>
                        <option value="ron">RON — Romanian Leu</option>
                        <option value="rpl">RPL — Rocket Pool</option>
                        <option value="rsd">RSD — Serbian Dinar</option>
                        <option value="rub">RUB — Russian Ruble</option>
                        <option value="rune">RUNE — THORChain (ERC20)</option>
                        <option value="rvn">RVN — Ravencoin</option>
                        <option value="rwf">RWF — Rwandan Franc</option>
                        <option value="sand">SAND — The Sandbox</option>
                        <option value="sar">SAR — Saudi Arabian Riyal</option>
                        <option value="sbd">SBD — Solomon Islander Dollar</option>
                        <option value="scr">SCR — Seychellois Rupee</option>
                        <option value="sdd">SDD — Sudanese Dinar</option>
                        <option value="sdg">SDG — Sudanese Pound</option>
                        <option value="sek">SEK — Swedish Krona</option>
                        <option value="sgd">SGD — Singapore Dollar</option>
                        <option value="shib">SHIB — Shiba Inu</option>
                        <option value="shp">SHP — Saint Helenian Pound</option>
                        <option value="sit">SIT — Slovenian Tolar</option>
                        <option value="skk">SKK — Slovak Koruna</option>
                        <option value="sle">SLE — Sierra Leonean Leone</option>
                        <option value="sll">SLL — Sierra Leonean Leone</option>
                        <option value="snx">SNX — Synthetix Network</option>
                        <option value="sol">SOL — Solana</option>
                        <option value="sos">SOS — Somali Shilling</option>
                        <option value="spl">SPL — Seborgan Luigino</option>
                        <option value="srd">SRD — Surinamese Dollar</option>
                        <option value="srg">SRG — Surinamese Guilder</option>
                        <option value="ssp">SSP — South Sudanese Pound</option>
                        <option value="std">STD — Sao Tomean Dobra</option>
                        <option value="stn">STN — Sao Tomean Dobra</option>
                        <option value="stx">STX — Stacks</option>
                        <option value="sui">SUI — Sui</option>
                        <option value="svc">SVC — Salvadoran Colon</option>
                        <option value="syp">SYP — Syrian Pound</option>
                        <option value="szl">SZL — Swazi Lilangeni</option>
                        <option value="thb">THB — Thai Baht</option>
                        <option value="theta">THETA — Theta</option>
                        <option value="tjs">TJS — Tajikistani Somoni</option>
                        <option value="tmm">TMM — Turkmenistani Manat</option>
                        <option value="tmt">TMT — Turkmenistani Manat</option>
                        <option value="tnd">TND — Tunisian Dinar</option>
                        <option value="top">TOP — Tongan Pa'anga</option>
                        <option value="trl">TRL — </option>
                        <option value="trx">TRX — TRON</option>
                        <option value="try">TRY — Turkish Lira</option>
                        <option value="ttd">TTD — Trinidadian Dollar</option>
                        <option value="tusd">TUSD — True USD</option>
                        <option value="tvd">TVD — Tuvaluan Dollar</option>
                        <option value="twd">TWD — Taiwan New Dollar</option>
                        <option value="twt">TWT — Trust Wallet Token</option>
                        <option value="tzs">TZS — Tanzanian Shilling</option>
                        <option value="uah">UAH — Ukrainian Hryvnia</option>
                        <option value="ugx">UGX — Ugandan Shilling</option>
                        <option value="uni">UNI — Uniswap</option>
                        <option value="usd" selected>USD — US Dollar</option>
                        <option value="usdc">USDC — USDC</option>
                        <option value="usdd">USDD — </option>
                        <option value="usdp">USDP — USDP Stablecoin</option>
                        <option value="usdt">USDT — Tether</option>
                        <option value="uyu">UYU — Uruguayan Peso</option>
                        <option value="uzs">UZS — Uzbekistani Som</option>
                        <option value="val">VAL — Vatican City Lira</option>
                        <option value="veb">VEB — Venezuelan Bolívar</option>
                        <option value="ved">VED — </option>
                        <option value="vef">VEF — Venezuelan Bolívar</option>
                        <option value="ves">VES — Venezuelan Bolívar</option>
                        <option value="vet">VET — Vechain</option>
                        <option value="vnd">VND — Vietnamese Dong</option>
                        <option value="vuv">VUV — Ni-Vanuatu Vatu</option>
                        <option value="waves">WAVES — Waves</option>
                        <option value="wemix">WEMIX — WEMIX</option>
                        <option value="woo">WOO — WOO Network</option>
                        <option value="wst">WST — Samoan Tala</option>
                        <option value="xaf">XAF — Central African CFA Franc BEAC</option>
                        <option value="xag">XAG — Silver Ounce</option>
                        <option value="xau">XAU — Gold Ounce</option>
                        <option value="xaut">XAUT — Tether Gold</option>
                        <option value="xbt">XBT — </option>
                        <option value="xcd">XCD — East Caribbean Dollar</option>
                        <option value="xcg">XCG — Xchange</option>
                        <option value="xch">XCH — Chia</option>
                        <option value="xdc">XDC — XDC Network</option>
                        <option value="xdr">XDR — IMF Special Drawing Rights</option>
                        <option value="xec">XEC — Eternal Coin</option>
                        <option value="xem">XEM — NEM</option>
                        <option value="xlm">XLM — Stellar Lumen</option>
                        <option value="xmr">XMR — Monero</option>
                        <option value="xof">XOF — CFA Franc</option>
                        <option value="xpd">XPD — Palladium Ounce</option>
                        <option value="xpf">XPF — CFP Franc</option>
                        <option value="xpt">XPT — Platinum Ounce</option>
                        <option value="xrp">XRP — Ripple</option>
                        <option value="xtz">XTZ — Tezos</option>
                        <option value="yer">YER — Yemeni Rial</option>
                        <option value="zar">ZAR — South African Rand</option>
                        <option value="zec">ZEC — ZCash</option>
                        <option value="zil">ZIL — Zilliqa</option>
                        <option value="zmk">ZMK — Zambian Kwacha</option>
                        <option value="zmw">ZMW — Zambian Kwacha</option>
                        <option value="zwd">ZWD — Zimbabwean Dollar</option>
                        <option value="zwg">ZWG — </option>
                        <option value="zwl">ZWL — Zimbabwean Dollar</option>
                        </select>
                    </div>
                </div>
                <button class="tc-cc-swap tc-btn tc-btn--ghost" type="button" title="Swap currencies">
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="17 1 21 5 17 9"/><path d="M3 11V9a4 4 0 0 1 4-4h14"/><polyline points="7 23 3 19 7 15"/><path d="M21 13v2a4 4 0 0 1-4 4H3"/></svg>
                </button>
                <div class="tc-input-group tc-cc-to-group">
                    <label class="tc-label">To</label>
                    <div class="tc-cc-select-wrap">
                        <input type="text" class="tc-input tc-cc-search tc-cc-to-search" placeholder="Search currency..." autocomplete="off">
                        <select class="tc-select tc-cc-to">
                        <option value="1inch">1INCH — 1inch</option>
                        <option value="aave">AAVE — Aave</option>
                        <option value="ada">ADA — Cardano</option>
                        <option value="aed">AED — Emirati Dirham</option>
                        <option value="afn">AFN — Afghan Afghani</option>
                        <option value="agix">AGIX — SingularityNET</option>
                        <option value="akt">AKT — Akash Network</option>
                        <option value="algo">ALGO — Algorand</option>
                        <option value="all">ALL — Albanian Lek</option>
                        <option value="amd">AMD — Armenian Dram</option>
                        <option value="amp">AMP — Amp</option>
                        <option value="ang">ANG — Dutch Guilder</option>
                        <option value="aoa">AOA — Angolan Kwanza</option>
                        <option value="ape">APE — ApeCoin</option>
                        <option value="apt">APT — Aptos</option>
                        <option value="ar">AR — Arweave</option>
                        <option value="arb">ARB — Arbitrum</option>
                        <option value="ars">ARS — Argentine Peso</option>
                        <option value="atom">ATOM — Cosmos</option>
                        <option value="ats">ATS — Austrian Schilling</option>
                        <option value="aud">AUD — Australian Dollar</option>
                        <option value="avax">AVAX — Avalanche</option>
                        <option value="awg">AWG — Aruban or Dutch Guilder</option>
                        <option value="axs">AXS — Axie Infinity</option>
                        <option value="azm">AZM — Azerbaijani Manat</option>
                        <option value="azn">AZN — Azerbaijan Manat</option>
                        <option value="bake">BAKE — BakeryToken</option>
                        <option value="bam">BAM — Bosnian Convertible Mark</option>
                        <option value="bat">BAT — Basic Attention Token</option>
                        <option value="bbd">BBD — Barbadian or Bajan Dollar</option>
                        <option value="bch">BCH — Bitcoin Cash</option>
                        <option value="bdt">BDT — Bangladeshi Taka</option>
                        <option value="bef">BEF — Belgian Franc</option>
                        <option value="bgn">BGN — Bulgarian Lev</option>
                        <option value="bhd">BHD — Bahraini Dinar</option>
                        <option value="bif">BIF — Burundian Franc</option>
                        <option value="bmd">BMD — Bermudian Dollar</option>
                        <option value="bnb">BNB — Binance Coin</option>
                        <option value="bnd">BND — Bruneian Dollar</option>
                        <option value="bob">BOB — Bolivian Bolíviano</option>
                        <option value="brl">BRL — Brazilian Real</option>
                        <option value="bsd">BSD — Bahamian Dollar</option>
                        <option value="bsv">BSV — Bitcoin SV</option>
                        <option value="bsw">BSW — Biswap</option>
                        <option value="btc">BTC — Bitcoin</option>
                        <option value="btcb">BTCB — Bitcoin BEP2</option>
                        <option value="btg">BTG — Bitcoin Gold</option>
                        <option value="btn">BTN — Bhutanese Ngultrum</option>
                        <option value="btt">BTT — BitTorrent</option>
                        <option value="busd">BUSD — Binance USD</option>
                        <option value="bwp">BWP — Botswana Pula</option>
                        <option value="byn">BYN — Belarusian Ruble</option>
                        <option value="byr">BYR — Belarusian Ruble</option>
                        <option value="bzd">BZD — Belizean Dollar</option>
                        <option value="cad">CAD — Canadian Dollar</option>
                        <option value="cake">CAKE — PancakeSwap</option>
                        <option value="cdf">CDF — Congolese Franc</option>
                        <option value="celo">CELO — Celo</option>
                        <option value="cfx">CFX — Conflux</option>
                        <option value="chf">CHF — Swiss Franc</option>
                        <option value="chz">CHZ — Chiliz</option>
                        <option value="clp">CLP — Chilean Peso</option>
                        <option value="cnh">CNH — Chinese Yuan Renminbi Offshore</option>
                        <option value="cny">CNY — Chinese Yuan Renminbi</option>
                        <option value="comp">COMP — Compound</option>
                        <option value="cop">COP — Colombian Peso</option>
                        <option value="crc">CRC — Costa Rican Colon</option>
                        <option value="cro">CRO — Crypto.com Chain</option>
                        <option value="crv">CRV — Curve DAO Token</option>
                        <option value="cspr">CSPR — Casper</option>
                        <option value="cuc">CUC — Cuban Convertible Peso</option>
                        <option value="cup">CUP — Cuban Peso</option>
                        <option value="cve">CVE — Cape Verdean Escudo</option>
                        <option value="cvx">CVX — Convex Finance</option>
                        <option value="cyp">CYP — Cypriot Pound</option>
                        <option value="czk">CZK — Czech Koruna</option>
                        <option value="dai">DAI — DAI</option>
                        <option value="dash">DASH — Digital Cash</option>
                        <option value="dcr">DCR — Decred</option>
                        <option value="dem">DEM — German Deutsche Mark</option>
                        <option value="dfi">DFI — DfiStarter</option>
                        <option value="djf">DJF — Djiboutian Franc</option>
                        <option value="dkk">DKK — Danish Krone</option>
                        <option value="doge">DOGE — Dogecoin</option>
                        <option value="dop">DOP — Dominican Peso</option>
                        <option value="dot">DOT — Polkadot</option>
                        <option value="dydx">DYDX — dYdX</option>
                        <option value="dzd">DZD — Algerian Dinar</option>
                        <option value="eek">EEK — Estonian Kroon</option>
                        <option value="egld">EGLD — Elrond</option>
                        <option value="egp">EGP — Egyptian Pound</option>
                        <option value="enj">ENJ — Enjin Coin</option>
                        <option value="eos">EOS — EOS</option>
                        <option value="ern">ERN — Eritrean Nakfa</option>
                        <option value="esp">ESP — Spanish Peseta</option>
                        <option value="etb">ETB — Ethiopian Birr</option>
                        <option value="etc">ETC — Ethereum Classic</option>
                        <option value="eth">ETH — Ethereum</option>
                        <option value="eur" selected>EUR — Euro</option>
                        <option value="eurc">EURC — </option>
                        <option value="fei">FEI — Fei USD</option>
                        <option value="fil">FIL — Filecoin</option>
                        <option value="fim">FIM — Finnish Markka</option>
                        <option value="fjd">FJD — Fijian Dollar</option>
                        <option value="fkp">FKP — Falkland Island Pound</option>
                        <option value="flow">FLOW — Flow</option>
                        <option value="flr">FLR — FLARE</option>
                        <option value="frax">FRAX — Frax</option>
                        <option value="frf">FRF — French Franc</option>
                        <option value="ftt">FTT — FarmaTrust</option>
                        <option value="gala">GALA — Gala</option>
                        <option value="gbp">GBP — British Pound</option>
                        <option value="gel">GEL — Georgian Lari</option>
                        <option value="ggp">GGP — Guernsey Pound</option>
                        <option value="ghc">GHC — Ghanaian Cedi</option>
                        <option value="ghs">GHS — Ghanaian Cedi</option>
                        <option value="gip">GIP — Gibraltar Pound</option>
                        <option value="gmd">GMD — Gambian Dalasi</option>
                        <option value="gmx">GMX — Goldmaxcoin</option>
                        <option value="gnf">GNF — Guinean Franc</option>
                        <option value="gno">GNO — Gnosis</option>
                        <option value="grd">GRD — Greek Drachma</option>
                        <option value="grt">GRT — The Graph</option>
                        <option value="gt">GT — GateToken</option>
                        <option value="gtq">GTQ — Guatemalan Quetzal</option>
                        <option value="gusd">GUSD — Gemini US Dollar</option>
                        <option value="gyd">GYD — Guyanese Dollar</option>
                        <option value="hbar">HBAR — Hedera</option>
                        <option value="hkd">HKD — Hong Kong Dollar</option>
                        <option value="hnl">HNL — Honduran Lempira</option>
                        <option value="hnt">HNT — Helium</option>
                        <option value="hot">HOT — Hydro Protocol</option>
                        <option value="hrk">HRK — Croatian Kuna</option>
                        <option value="ht">HT — Huobi Token</option>
                        <option value="htg">HTG — Haitian Gourde</option>
                        <option value="huf">HUF — Hungarian Forint</option>
                        <option value="icp">ICP — Internet Computer</option>
                        <option value="idr">IDR — Indonesian Rupiah</option>
                        <option value="iep">IEP — Irish Pound</option>
                        <option value="ils">ILS — Israeli Shekel</option>
                        <option value="imp">IMP — Isle of Man Pound</option>
                        <option value="imx">IMX — Immutable X</option>
                        <option value="inj">INJ — Injective</option>
                        <option value="inr">INR — Indian Rupee</option>
                        <option value="iqd">IQD — Iraqi Dinar</option>
                        <option value="irr">IRR — Iranian Rial</option>
                        <option value="isk">ISK — Icelandic Krona</option>
                        <option value="itl">ITL — Italian Lira</option>
                        <option value="jep">JEP — Jersey Pound</option>
                        <option value="jmd">JMD — Jamaican Dollar</option>
                        <option value="jod">JOD — Jordanian Dinar</option>
                        <option value="jpy">JPY — Japanese Yen</option>
                        <option value="kas">KAS — </option>
                        <option value="kava">KAVA — Kava</option>
                        <option value="kcs">KCS — Kucoin</option>
                        <option value="kda">KDA — Kadena</option>
                        <option value="kes">KES — Kenyan Shilling</option>
                        <option value="kgs">KGS — Kyrgyzstani Som</option>
                        <option value="khr">KHR — Cambodian Riel</option>
                        <option value="klay">KLAY — Klaytn</option>
                        <option value="kmf">KMF — Comorian Franc</option>
                        <option value="knc">KNC — Kyber Network Crystals</option>
                        <option value="kpw">KPW — North Korean Won</option>
                        <option value="krw">KRW — South Korean Won</option>
                        <option value="ksm">KSM — Kusama</option>
                        <option value="kwd">KWD — Kuwaiti Dinar</option>
                        <option value="kyd">KYD — Caymanian Dollar</option>
                        <option value="kzt">KZT — Kazakhstani Tenge</option>
                        <option value="lak">LAK — Lao Kip</option>
                        <option value="lbp">LBP — Lebanese Pound</option>
                        <option value="ldo">LDO — Lido DAO Token</option>
                        <option value="leo">LEO — LEOcoin</option>
                        <option value="link">LINK — Chainlink</option>
                        <option value="lkr">LKR — Sri Lankan Rupee</option>
                        <option value="lrc">LRC — Loopring</option>
                        <option value="lrd">LRD — Liberian Dollar</option>
                        <option value="lsl">LSL — Basotho Loti</option>
                        <option value="ltc">LTC — Litecoin</option>
                        <option value="ltl">LTL — Lithuanian Litas</option>
                        <option value="luf">LUF — Luxembourg Franc</option>
                        <option value="luna">LUNA — Terra</option>
                        <option value="lunc">LUNC — </option>
                        <option value="lvl">LVL — Latvian Lat</option>
                        <option value="lyd">LYD — Libyan Dinar</option>
                        <option value="mad">MAD — Moroccan Dirham</option>
                        <option value="mana">MANA — Mana Coin Decentraland</option>
                        <option value="mbx">MBX — MobieCoin</option>
                        <option value="mdl">MDL — Moldovan Leu</option>
                        <option value="mga">MGA — Malagasy Ariary</option>
                        <option value="mgf">MGF — Malagasy Franc</option>
                        <option value="mina">MINA — Mina</option>
                        <option value="mkd">MKD — Macedonian Denar</option>
                        <option value="mkr">MKR — Maker</option>
                        <option value="mmk">MMK — Burmese Kyat</option>
                        <option value="mnt">MNT — Mongolian Tughrik</option>
                        <option value="mop">MOP — Macau Pataca</option>
                        <option value="mro">MRO — Mauritanian Ouguiya</option>
                        <option value="mru">MRU — Mauritanian Ouguiya</option>
                        <option value="mtl">MTL — Maltese Lira</option>
                        <option value="mur">MUR — Mauritian Rupee</option>
                        <option value="mvr">MVR — Maldivian Rufiyaa</option>
                        <option value="mwk">MWK — Malawian Kwacha</option>
                        <option value="mxn">MXN — Mexican Peso</option>
                        <option value="mxv">MXV — </option>
                        <option value="myr">MYR — Malaysian Ringgit</option>
                        <option value="mzm">MZM — Mozambican Metical</option>
                        <option value="mzn">MZN — Mozambican Metical</option>
                        <option value="nad">NAD — Namibian Dollar</option>
                        <option value="near">NEAR — NEAR Protocol</option>
                        <option value="neo">NEO — NEO</option>
                        <option value="nexo">NEXO — NEXO</option>
                        <option value="nft">NFT — NFT</option>
                        <option value="ngn">NGN — Nigerian Naira</option>
                        <option value="nio">NIO — Nicaraguan Cordoba</option>
                        <option value="nlg">NLG — Dutch Guilder</option>
                        <option value="nok">NOK — Norwegian Krone</option>
                        <option value="npr">NPR — Nepalese Rupee</option>
                        <option value="nzd">NZD — New Zealand Dollar</option>
                        <option value="okb">OKB — Okex</option>
                        <option value="omr">OMR — Omani Rial</option>
                        <option value="one">ONE — Menlo One</option>
                        <option value="op">OP — Optimism</option>
                        <option value="ordi">ORDI — </option>
                        <option value="pab">PAB — Panamanian Balboa</option>
                        <option value="paxg">PAXG — PAX Gold</option>
                        <option value="pen">PEN — Peruvian Sol</option>
                        <option value="pepe">PEPE — </option>
                        <option value="pgk">PGK — Papua New Guinean Kina</option>
                        <option value="php">PHP — Philippine Peso</option>
                        <option value="pi">PI — Plian</option>
                        <option value="pkr">PKR — Pakistani Rupee</option>
                        <option value="pln">PLN — Polish Zloty</option>
                        <option value="pol">POL — Proof Of Liquidity</option>
                        <option value="pte">PTE — Portuguese Escudo</option>
                        <option value="pyg">PYG — Paraguayan Guarani</option>
                        <option value="qar">QAR — Qatari Riyal</option>
                        <option value="qnt">QNT — Quant</option>
                        <option value="qtum">QTUM — QTUM</option>
                        <option value="rol">ROL — Romanian Leu</option>
                        <option value="ron">RON — Romanian Leu</option>
                        <option value="rpl">RPL — Rocket Pool</option>
                        <option value="rsd">RSD — Serbian Dinar</option>
                        <option value="rub">RUB — Russian Ruble</option>
                        <option value="rune">RUNE — THORChain (ERC20)</option>
                        <option value="rvn">RVN — Ravencoin</option>
                        <option value="rwf">RWF — Rwandan Franc</option>
                        <option value="sand">SAND — The Sandbox</option>
                        <option value="sar">SAR — Saudi Arabian Riyal</option>
                        <option value="sbd">SBD — Solomon Islander Dollar</option>
                        <option value="scr">SCR — Seychellois Rupee</option>
                        <option value="sdd">SDD — Sudanese Dinar</option>
                        <option value="sdg">SDG — Sudanese Pound</option>
                        <option value="sek">SEK — Swedish Krona</option>
                        <option value="sgd">SGD — Singapore Dollar</option>
                        <option value="shib">SHIB — Shiba Inu</option>
                        <option value="shp">SHP — Saint Helenian Pound</option>
                        <option value="sit">SIT — Slovenian Tolar</option>
                        <option value="skk">SKK — Slovak Koruna</option>
                        <option value="sle">SLE — Sierra Leonean Leone</option>
                        <option value="sll">SLL — Sierra Leonean Leone</option>
                        <option value="snx">SNX — Synthetix Network</option>
                        <option value="sol">SOL — Solana</option>
                        <option value="sos">SOS — Somali Shilling</option>
                        <option value="spl">SPL — Seborgan Luigino</option>
                        <option value="srd">SRD — Surinamese Dollar</option>
                        <option value="srg">SRG — Surinamese Guilder</option>
                        <option value="ssp">SSP — South Sudanese Pound</option>
                        <option value="std">STD — Sao Tomean Dobra</option>
                        <option value="stn">STN — Sao Tomean Dobra</option>
                        <option value="stx">STX — Stacks</option>
                        <option value="sui">SUI — Sui</option>
                        <option value="svc">SVC — Salvadoran Colon</option>
                        <option value="syp">SYP — Syrian Pound</option>
                        <option value="szl">SZL — Swazi Lilangeni</option>
                        <option value="thb">THB — Thai Baht</option>
                        <option value="theta">THETA — Theta</option>
                        <option value="tjs">TJS — Tajikistani Somoni</option>
                        <option value="tmm">TMM — Turkmenistani Manat</option>
                        <option value="tmt">TMT — Turkmenistani Manat</option>
                        <option value="tnd">TND — Tunisian Dinar</option>
                        <option value="top">TOP — Tongan Pa'anga</option>
                        <option value="trl">TRL — </option>
                        <option value="trx">TRX — TRON</option>
                        <option value="try">TRY — Turkish Lira</option>
                        <option value="ttd">TTD — Trinidadian Dollar</option>
                        <option value="tusd">TUSD — True USD</option>
                        <option value="tvd">TVD — Tuvaluan Dollar</option>
                        <option value="twd">TWD — Taiwan New Dollar</option>
                        <option value="twt">TWT — Trust Wallet Token</option>
                        <option value="tzs">TZS — Tanzanian Shilling</option>
                        <option value="uah">UAH — Ukrainian Hryvnia</option>
                        <option value="ugx">UGX — Ugandan Shilling</option>
                        <option value="uni">UNI — Uniswap</option>
                        <option value="usd">USD — US Dollar</option>
                        <option value="usdc">USDC — USDC</option>
                        <option value="usdd">USDD — </option>
                        <option value="usdp">USDP — USDP Stablecoin</option>
                        <option value="usdt">USDT — Tether</option>
                        <option value="uyu">UYU — Uruguayan Peso</option>
                        <option value="uzs">UZS — Uzbekistani Som</option>
                        <option value="val">VAL — Vatican City Lira</option>
                        <option value="veb">VEB — Venezuelan Bolívar</option>
                        <option value="ved">VED — </option>
                        <option value="vef">VEF — Venezuelan Bolívar</option>
                        <option value="ves">VES — Venezuelan Bolívar</option>
                        <option value="vet">VET — Vechain</option>
                        <option value="vnd">VND — Vietnamese Dong</option>
                        <option value="vuv">VUV — Ni-Vanuatu Vatu</option>
                        <option value="waves">WAVES — Waves</option>
                        <option value="wemix">WEMIX — WEMIX</option>
                        <option value="woo">WOO — WOO Network</option>
                        <option value="wst">WST — Samoan Tala</option>
                        <option value="xaf">XAF — Central African CFA Franc BEAC</option>
                        <option value="xag">XAG — Silver Ounce</option>
                        <option value="xau">XAU — Gold Ounce</option>
                        <option value="xaut">XAUT — Tether Gold</option>
                        <option value="xbt">XBT — </option>
                        <option value="xcd">XCD — East Caribbean Dollar</option>
                        <option value="xcg">XCG — Xchange</option>
                        <option value="xch">XCH — Chia</option>
                        <option value="xdc">XDC — XDC Network</option>
                        <option value="xdr">XDR — IMF Special Drawing Rights</option>
                        <option value="xec">XEC — Eternal Coin</option>
                        <option value="xem">XEM — NEM</option>
                        <option value="xlm">XLM — Stellar Lumen</option>
                        <option value="xmr">XMR — Monero</option>
                        <option value="xof">XOF — CFA Franc</option>
                        <option value="xpd">XPD — Palladium Ounce</option>
                        <option value="xpf">XPF — CFP Franc</option>
                        <option value="xpt">XPT — Platinum Ounce</option>
                        <option value="xrp">XRP — Ripple</option>
                        <option value="xtz">XTZ — Tezos</option>
                        <option value="yer">YER — Yemeni Rial</option>
                        <option value="zar">ZAR — South African Rand</option>
                        <option value="zec">ZEC — ZCash</option>
                        <option value="zil">ZIL — Zilliqa</option>
                        <option value="zmk">ZMK — Zambian Kwacha</option>
                        <option value="zmw">ZMW — Zambian Kwacha</option>
                        <option value="zwd">ZWD — Zimbabwean Dollar</option>
                        <option value="zwg">ZWG — </option>
                        <option value="zwl">ZWL — Zimbabwean Dollar</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="tc-cc-manual-rate" style="display:none">
                <div class="tc-input-group">
                    <label class="tc-label">Custom Exchange Rate (optional)</label>
                    <input type="number" class="tc-input tc-cc-custom-rate" step="any" placeholder="e.g., 0.85">
                </div>
            </div>
        </div>
        <div class="tc-actions">
            <button class="tc-btn tc-btn--accent" id="tc-cc-convert" type="button">Convert</button>
            <button class="tc-btn tc-btn--ghost" id="tc-cc-toggle-rate" type="button">Use Custom Rate</button>
            <button class="tc-btn tc-btn--ghost" id="tc-cc-copy" type="button">Copy Result</button>
        </div>
        <div class="tc-cc-status" id="tc-cc-status"></div>
        <?php
    }

    protected function render_result_content(array $settings): void {
        ?>
        <div class="tc-cc-result-panel" id="tc-cc-result-panel" style="display:none">
            <div class="tc-cc-result-card">
                <div class="tc-cc-result-from" id="tc-cc-result-from">—</div>
                <div class="tc-cc-result-equals">=</div>
                <div class="tc-cc-result-to" id="tc-cc-result-to">—</div>
                <div class="tc-cc-result-rate" id="tc-cc-result-rate">—</div>
            </div>
            <div class="tc-cc-result-details" id="tc-cc-result-details"></div>
        </div>
        <?php
    }

    protected function render_result(array $settings): void {
        ?>
        <div class="tc-result-col">
            <div class="tc-panel">
                <div class="tc-panel-head">
                    <h3>2 · Conversion Result</h3>
                    <span id="tc-status-chip">Idle</span>
                </div>
                <div class="tc-panel-body">
                    <div class="tc-stats">
                        <div><span>From</span><b id="tc-stat-orig">—</b></div>
                        <div><span>To</span><b id="tc-stat-comp">—</b></div>
                        <div class="saved"><span>Rate</span><b id="tc-stat-saved">—</b></div>
                    </div>
                    <?php $this->render_result_content($settings); ?>
                </div>
            </div>
            <?php $this->render_side_panel($settings); ?>
        </div>
        <?php
    }
}
